export const previewData = {
  date: 'Saturday, September 19',
  greeting: 'A little every day.',
  dailyLimit: 30,
  completed: 12,
  due: 18,
  newCards: 5,
  streak: 6,
  reviewMinutes: 14,
  courses: [
    {
      id: 'calculo3',
      name: 'Cálculo 3',
      shortName: 'Cálculo',
      topic: 'Producto cruz y planos',
      source: 'Semana 2 · diapositivas',
      due: 9,
      color: '#D9A981',
    },
    {
      id: 'softeng',
      name: 'Ingeniería de Software',
      shortName: 'Software',
      topic: 'Diseño de arquitectura',
      source: 'Unidad 2 · material de clase',
      due: 6,
      color: '#91B2CB',
    },
    {
      id: 'books',
      name: 'Reading',
      shortName: 'Books',
      topic: 'Las 48 leyes del poder',
      source: 'Your highlights',
      due: 3,
      color: '#B6A0CC',
    },
  ],
  card: {
    course: 'Cálculo 3',
    topic: 'Producto cruz',
    type: 'Basic',
    question: 'What does the magnitude of the cross product of two vectors represent?',
    answer: 'The area of the parallelogram spanned by those vectors.',
    source: 'Semana 2 · producto cruz',
    citation: 'Section 12.4',
    progress: '13 of 30',
  },
  book: {
    title: 'Las 48 leyes del poder',
    author: 'Robert Greene',
    currentPage: 84,
    lastSession: 'Today',
    highlights: 12,
    newCards: 2,
  },
} as const;
